### PR TITLE
Tinymce

### PR DESCRIPTION
**Pull request by 0styx0**
Adds tinymce to the project. Solves issue #10 
Note: Tinymce will bug you about an api key (which is free), but since I'm just a random person on the internet, I didn't want to register one for you. (When you go to builder.php you'll see the prompt)

### CODE REVIEW

**Comment by alexmorley** [comment]
Awesome thanks for your help! Super busy today but will get round to reviewing this fully this week (probably today or tomorrow).

**Comment by 0styx0** [comment]
Ok 😀

**Comment by alexmorley** [comment]
Wicked. I've had a look through and it looks good! Thanks a bunch.

**Review by alexmorley — APPROVED** [review]

**Review by alexmorley — CHANGES_REQUESTED** [review]
At the moment this breaks the download function. Will need to fix that before merging this. Maybe... It would be cool to be able to flick between this editor and the contenteditable - just so saving as a pdf with the websites default styling might still work.

**Comment by alexmorley** [comment]
Was the download working for you or no? What do you think is the best way to go ? :thinking:

**Comment by 0styx0** [comment]
The download doesn't work for me, but I don't think it's anything I've done. When I switched to the development or master branch (which I didn't make any changes to) I still get the following error when reading a download: `Warning: readfile(license_tmp/your_licence.84632975.odt): failed to open stream: No such file or directory in /path/to/CodeOfConduct.Builder/app/download.php on line 6`

I see there's something above about changes requested but I don't know what to do with that, I'm pretty new to contributing to projects

**Comment by alexmorley** [comment]
So the reason (I think) the downloads won't work on your computer is either - you are just viewing the files on the filesystem instead of running a local server? - or the server (i use apache) doesn't have write permissions to the directory where the files are created (that always bites me).

The "changes requested" is just a note to myself not to merge this until things are fixed, nothing to worry about :smile:. I'm pretty new to managing projects so we're both out of our comfort zone!

**Comment by 0styx0** [comment]
Running mamp (apache) pointed at app/. The site loads fine, files in this project directory are changed to 777 permissions, same error when reading the downloaded files

**Comment by alexmorley** [comment]
Hmmm, not sure. I kept on running into weird bugs like this which is why I just use it a docker image now (but that's a bit hefty download). Could you open an issue and paste a few details? Thanks!

**Comment by alexmorley** [comment]
Closing this one and merging #38 instead.

**Pull request closed without merging**
